# Generated by Django 4.0.4 on 2022-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='person_tag',
            field=models.ManyToManyField(blank=True, to='single_page.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stock_tag',
            field=models.ManyToManyField(blank=True, to='single_page.stock'),
        ),
        migrations.AlterField(
            model_name='event',
            name='word_tag',
            field=models.ManyToManyField(blank=True, to='single_page.word'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='stock_tag',
            field=models.ManyToManyField(blank=True, to='single_page.stock'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='word_tag',
            field=models.ManyToManyField(blank=True, to='single_page.word'),
        ),
        migrations.AlterField(
            model_name='person',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
