# Generated by Django 4.0.4 on 2022-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0002_remove_stock_slug_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
