# Generated by Django 4.0.4 on 2022-06-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0003_alter_stock_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
