# Generated by Django 4.0.4 on 2022-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0008_alter_event_content_alter_opinion_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
