# Generated by Django 4.0.4 on 2022-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0009_stock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
