# Generated by Django 4.0.4 on 2022-07-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0010_alter_stock_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='slug',
        ),
    ]
