# Generated by Django 4.0.4 on 2022-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0011_remove_stock_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='short',
            new_name='title',
        ),
    ]
