# Generated by Django 4.0.4 on 2022-07-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0012_rename_short_opinion_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='name',
            new_name='person_tag',
        ),
    ]
