# Generated by Django 4.0.4 on 2022-07-18 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('single_page', '0013_rename_name_opinion_person_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('content', markdownx.models.MarkdownxField(blank=True, default='')),
                ('category', models.CharField(choices=[('EV', 'Event'), ('OP', 'Opinion'), ('RE', 'Report')], default='EV', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('content', markdownx.models.MarkdownxField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='person_tag',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='stock_tag',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='word_tag',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='block',
            name='speaker',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_speaker', to='single_page.wiki'),
        ),
        migrations.AddField(
            model_name='block',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='block_tag', to='single_page.wiki'),
        ),
    ]
