# Generated by Django 4.0.4 on 2022-07-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0014_block_wiki_remove_opinion_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', to='single_page.wiki'),
        ),
    ]
