# Generated by Django 4.0.4 on 2022-07-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0015_wiki_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='category',
            field=models.CharField(choices=[('COR', '기업'), ('IAT', '산업/테마'), ('MAR', '시장'), ('WOR', '단어'), ('MEV', '주요사건'), ('COM', '원자재'), ('CRY', '암호화폐'), ('EVG', '사건분류')], default='COR', max_length=3),
        ),
    ]
