# Generated by Django 4.0.4 on 2022-07-18 16:24

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice', markdownx.models.MarkdownxField(blank=True, default='')),
                ('Project', markdownx.models.MarkdownxField(blank=True, default='')),
                ('ToDoList', markdownx.models.MarkdownxField(blank=True, default='')),
            ],
        ),
    ]
