# Generated by Django 4.0.4 on 2022-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_notice_home_textfield_remove_home_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='TextField',
            new_name='textfield',
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
