# Generated by Django 4.0.4 on 2022-07-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_textfield_home_textfield_home_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ('pk',)},
        ),
    ]
